version: "3.7"

services:

  api:
    build:
      context: .
    image: {{projectName}}
    container_name: {{projectName}}-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
{{#hasDepends}}
    links:
{{/hasDepends}}
{{#if_eq transporter "NATS"}}
      - nats
{{/if_eq}}
{{#redis}}
      - redis
{{/redis}}
{{#if_eq transporter "MQTT"}}
      - mqtt
{{/if_eq}}
{{#if_eq transporter "AMQP"}}
      - amqp
{{/if_eq}}
{{#if_eq transporter "STAN"}}
      - stan
{{/if_eq}}
{{#if_eq transporter "Kafka"}}
      - zookeeper
{{/if_eq}}
{{#hasDepends}}
    depends_on:
{{/hasDepends}}
{{#if_eq transporter "NATS"}}
      - nats
{{/if_eq}}
{{#redis}}
      - redis
{{/redis}}
{{#if_eq transporter "MQTT"}}
      - mqtt
{{/if_eq}}
{{#if_eq transporter "AMQP"}}
      - amqp
{{/if_eq}}
{{#if_eq transporter "STAN"}}
      - stan
{{/if_eq}}
{{#if_eq transporter "Kafka"}}
      - zookeeper
{{/if_eq}}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  greeter:
    image: {{projectName}}
    container_name: {{projectName}}-greeter
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    labels:
      - "traefik.enable=false"
      - "traefik.docker.network=internal"
{{#hasDepends}}
    links:
{{/hasDepends}}
{{#if_eq transporter "NATS"}}
      - nats
{{/if_eq}}
{{#redis}}
      - redis
{{/redis}}
{{#if_eq transporter "MQTT"}}
      - mqtt
{{/if_eq}}
{{#if_eq transporter "AMQP"}}
      - amqp
{{/if_eq}}
{{#if_eq transporter "STAN"}}
      - stan
{{/if_eq}}
{{#if_eq transporter "Kafka"}}
      - zookeeper
{{/if_eq}}
{{#hasDepends}}
    depends_on:
{{/hasDepends}}
{{#if_eq transporter "NATS"}}
      - nats
{{/if_eq}}
{{#redis}}
      - redis
{{/redis}}
{{#if_eq transporter "MQTT"}}
      - mqtt
{{/if_eq}}
{{#if_eq transporter "AMQP"}}
      - amqp
{{/if_eq}}
{{#if_eq transporter "STAN"}}
      - stan
{{/if_eq}}
{{#if_eq transporter "Kafka"}}
      - zookeeper
{{/if_eq}}

{{#if_eq transporter "NATS"}}

  nats:
    image: nats
    container_name: NATS
    labels:
      - "traefik.enable=false"
      - "traefik.docker.network=internal"
    networks:
      - internal
{{/if_eq}}
{{#redis}}

  redis:
    image: redis:alpine
    container_name: Redis
    labels:
      - "traefik.enable=false"
      - "traefik.docker.network=internal"
{{/redis}}
{{#if_eq transporter "MQTT"}}

  mqtt:
    image: ncarlier/mqtt
    container_name: MQTT
    labels:
      - "traefik.enable=false"
      - "traefik.docker.network=internal"
{{/if_eq}}
{{#if_eq transporter "AMQP"}}

  amqp:
    image: rabbitmq:3
    container_name: RabbitMQ
    labels:
      - "traefik.enable=false"
      - "traefik.docker.network=internal"
{{/if_eq}}
{{#if_eq transporter "STAN"}}

  stan:
    image: nats-streaming
    container_name: STAN
    labels:
      - "traefik.enable=false"
      - "traefik.docker.network=internal"
{{/if_eq}}
{{#if_eq transporter "Kafka"}}

  zookeeper:
    image: bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
{{/if_eq}}

  traefik:
    image: traefik
    container_name: traefik
    command:
      - "--api"
      - "--docker"
      - "--docker.usebindportip"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=docker.localhost"
      - "--docker.watch"
      - "--logLevel=INFO"
      - "--docker.network=web"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - internal
      - web
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  internal:
  web:
    external: true